version: '3.8'

services:
  flask_gunicorn:
    volumes:
      - static:/static
      - agentdata:/agentdata
    env_file:
      - approject/.env.local
    build:
      context: .
    privileged: true
    network_mode: host
    expose:
      - "8000"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - flask_gunicorn

volumes:
  static:       # not really used by the agent right now as it does not provide any particular web page
  agentdata:    # volume to hold agent json credential files