# Generated by Django 5.0.1 on 2024-02-24 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoHistory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(blank=True, max_length=64, null=True)),
                ('user_info', models.TextField(blank=True, null=True)),
                ('capture_time', models.DateTimeField(auto_now_add=True)),
                ('area', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seizure',
            fields=[
                ('email', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordHash',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asleap', models.CharField(blank=True, max_length=256, null=True)),
                ('jtr', models.CharField(blank=True, max_length=256, null=True)),
                ('hashcat', models.CharField(blank=True, max_length=256, null=True)),
                ('info_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apscavenge.infohistory')),
            ],
        ),
        migrations.AddField(
            model_name='infohistory',
            name='seizure_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apscavenge.seizure'),
        ),
    ]
