version: '3.8'

services:
  postgresql:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: apscavengedb
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - approject/.env.local
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
  pgdata: